from typing import Dict, Any
from nexora.genai.adapter_interface import GenAIAdapter
from nexora.core.config import Config

class MockGenAIAdapter(GenAIAdapter):
    """
    Mock LLM adapter that returns a hardcoded template response.
    Useful for testing the pipeline without incurring API costs.
    """
    
    def __init__(self):
        self.logger = Config.get_logger("MockGenAI")

    def generate_narrative(self, context: Dict[str, Any], prompt_template: str) -> str:
        self.logger.info("Generating narrative (MOCK)...")
        
        # Simulate processing the context
        metrics = context.get("metrics", {})
        
        return f"""
        [EXECUTIVE SUMMARY GENERATED BY MOCK AI]
        
        The model performed with an Accuracy/R2 of {list(metrics.values())[0] if metrics else 'N/A'}.
        This indicates a strong predictive capability.
        
        Key drivers identified include the supplied features.
        Recommendation: Deploy to staging for further validation.
        """
